### ISSUE TITLE
Current UI does not update properly when loading project

### ISSUE THREAD

**Issue by gkjohnson** [highcharts/highcharts-editor#153]
This might be two different bugs, but I'll list them here together:

1. Go to http://editor.highcharts.com/full.html
1. Create a line chart with markers from the sample data templates
1. Change the chart title to "TEST" in the _Customize/Titles_ pane
1. Select "save project" from the gear icon in the top right of the page
1. Refresh the page
1. Navigate to the _Custom/Title_ pane again
1. Load the previously saved project
1. **Note that the chart's title is "TEST", but the input field lists the default chart title**
1. Navigate away from this pane and then back. The input field properly lists the title as "TEST"
1. Navigate to the _Customize/Data Series_ pane
1. **Note that the chart graphs have markers but the "enable point markers" checkbox is not checked**
1. Toggling the checkbox twice disables the markers in the chart.

**Comment by cvasseng** [comment]
Hi, 

this should be fixed in the latest release, which just went live.

**Comment by gkjohnson** [comment]
Hey!

I had no idea a new release was so imminent! It does look like both of the issues I mentioned are still present in the new vesion. Do I have to save and load a new project? I was using the project I had exported yesterday.

Thanks!
